import React from 'react'

const LazyLoading = () => {
  return (
    <div>
     <p>Sure! Here’s a brief text: "In the heart of the bustling city, a small park offers a serene escape. Tall trees provide shade, while vibrant flowers bloom in colorful patches, attracting bees and butterflies. Visitors can be seen lounging on benches, reading or enjoying a quiet moment away from the city's hustle. The gentle sound of a nearby fountain and the laughter of children playing create a comforting ambiance, reminding everyone of the simple joys of nature."</p> 

     <p>Sure! Here’s a brief text: "In the heart of the bustling city, a small park offers a serene escape. Tall trees provide shade, while vibrant flowers bloom in colorful patches, attracting bees and butterflies. Visitors can be seen lounging on benches, reading or enjoying a quiet moment away from the city's hustle. The gentle sound of a nearby fountain and the laughter of children playing create a comforting ambiance, reminding everyone of the simple joys of nature."</p> 
     <p>Sure! Here’s a brief text: "In the heart of the bustling city, a small park offers a serene escape. Tall trees provide shade, while vibrant flowers bloom in colorful patches, attracting bees and butterflies. Visitors can be seen lounging on benches, reading or enjoying a quiet moment away from the city's hustle. The gentle sound of a nearby fountain and the laughter of children playing create a comforting ambiance, reminding everyone of the simple joys of nature."</p> 
     <p>Sure! Here’s a brief text: "In the heart of the bustling city, a small park offers a serene escape. Tall trees provide shade, while vibrant flowers bloom in colorful patches, attracting bees and butterflies. Visitors can be seen lounging on benches, reading or enjoying a quiet moment away from the city's hustle. The gentle sound of a nearby fountain and the laughter of children playing create a comforting ambiance, reminding everyone of the simple joys of nature."</p> 
     <p>Sure! Here’s a brief text: "In the heart of the bustling city, a small park offers a serene escape. Tall trees provide shade, while vibrant flowers bloom in colorful patches, attracting bees and butterflies. Visitors can be seen lounging on benches, reading or enjoying a quiet moment away from the city's hustle. The gentle sound of a nearby fountain and the laughter of children playing create a comforting ambiance, reminding everyone of the simple joys of nature."</p> 
     <p>Sure! Here’s a brief text: "In the heart of the bustling city, a small park offers a serene escape. Tall trees provide shade, while vibrant flowers bloom in colorful patches, attracting bees and butterflies. Visitors can be seen lounging on benches, reading or enjoying a quiet moment away from the city's hustle. The gentle sound of a nearby fountain and the laughter of children playing create a comforting ambiance, reminding everyone of the simple joys of nature."</p> 
     <p>Sure! Here’s a brief text: "In the heart of the bustling city, a small park offers a serene escape. Tall trees provide shade, while vibrant flowers bloom in colorful patches, attracting bees and butterflies. Visitors can be seen lounging on benches, reading or enjoying a quiet moment away from the city's hustle. The gentle sound of a nearby fountain and the laughter of children playing create a comforting ambiance, reminding everyone of the simple joys of nature."</p> 
     <p>Sure! Here’s a brief text: "In the heart of the bustling city, a small park offers a serene escape. Tall trees provide shade, while vibrant flowers bloom in colorful patches, attracting bees and butterflies. Visitors can be seen lounging on benches, reading or enjoying a quiet moment away from the city's hustle. The gentle sound of a nearby fountain and the laughter of children playing create a comforting ambiance, reminding everyone of the simple joys of nature."</p> 
        <p>Sure! Here’s a brief text: "In the heart of the bustling city, a small park offers a serene escape. Tall trees provide shade, while vibrant flowers bloom in colorful patches, attracting bees and butterflies. Visitors can be seen lounging on benches, reading or enjoying a quiet moment away from the city's hustle. The gentle sound of a nearby fountain and the laughter of children playing create a comforting ambiance, reminding everyone of the simple joys of nature."</p> 

    </div>
  )
}

export default LazyLoading
